module.exports = {
  REQUEST_SOURCES: "REQUEST_SOURCES",
  SOURCE_SELECTED: "SOURCE_SELECTED",
  SAVE_VIDEO: "SAVE_VIDEO",
  USER_CANCELLED: "USER_CANCELLED",
  COMPRESSED_VIDEO: "COMPRESSED_VIDEO",
};
